spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

---
spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    platform: h2
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver




#spring:
#  profiles:
#    active: local
#
#---
#spring:
#  profiles: local
#
#  jpa:
#    database-platform: H2
#    show-sql: false
#    hibernate:
#      ddl-auto: create-drop